-- MySQL Script generated by MySQL Workbench
-- Wed Dec  5 18:10:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema defesacivil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema defesacivil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `defesacivil` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `defesacivil` ;

-- -----------------------------------------------------
-- Table `defesacivil`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`endereco` (
  `endereco_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `regiao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`endereco_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6034
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`departamento` (
  `departamento_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `numero_residencia` INT(11) NULL DEFAULT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  `endereco_id` INT(11) NOT NULL,
  PRIMARY KEY (`departamento_id`),
  INDEX `fk_departamento_endereco1_idx` (`endereco_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`funcionario` (
  `funcionario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`funcionario_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`origem_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`origem_ocorrencia` (
  `origem_ocorrencia_id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`origem_ocorrencia_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`tipo_solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`tipo_solicitante` (
  `tipo_solicitante_id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`tipo_solicitante_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`solicitante` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `numero_residencia` INT(11) NULL DEFAULT NULL,
  `tipo_solicitante_id` INT(11) NOT NULL,
  `endereco_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solicitante_tipo_solicitante1_idx` (`tipo_solicitante_id` ASC) VISIBLE,
  INDEX `fk_solicitante_endereco1_idx` (`endereco_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`tipo_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`tipo_ocorrencia` (
  `tipo_ocorrencia_id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`tipo_ocorrencia_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`ocorrencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_abertura` DATETIME NULL DEFAULT NULL,
  `data_atendimento` DATETIME NULL DEFAULT NULL,
  `data_conclusao` DATETIME NULL DEFAULT NULL,
  `historico_inicial` VARCHAR(300) NULL DEFAULT NULL,
  `numero_local` INT(11) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `agente_id` INT(11) NULL DEFAULT NULL,
  `origem_ocorrencia_id` INT(11) NOT NULL,
  `solicitante_id` INT(11) NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  `endereco_endereco_id` INT(11) NOT NULL,
  `tipo_ocorrencia_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK2s0svsswi14154exs278aatem` (`agente_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_origem_ocorrencia_idx` (`origem_ocorrencia_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_solicitante1_idx` (`solicitante_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_endereco1_idx` (`endereco_endereco_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_tipo_ocorrencia1_idx` (`tipo_ocorrencia_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`perfis` (
  `perfis` INT(11) NULL DEFAULT NULL,
  `funcionario_funcionario_id` INT(11) NOT NULL,
  INDEX `fk_perfis_funcionario1_idx` (`funcionario_funcionario_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`tramitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`tramitacao` (
  `tramitacao_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cod` INT(11) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`tramitacao_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`relatorio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_local` INT(11) NULL DEFAULT NULL,
  `observacao` VARCHAR(1200) NULL DEFAULT NULL,
  `vistoria` VARCHAR(1200) NULL DEFAULT NULL,
  `endereco_id` INT(11) NULL DEFAULT NULL,
  `tramitacao_id` INT(11) NOT NULL,
  `ocorrencia_id` INT(11) NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK85lildukfk4q65hlpqq72b045` (`endereco_id` ASC) VISIBLE,
  INDEX `fk_relatorio_tramitacao1_idx` (`tramitacao_id` ASC) VISIBLE,
  INDEX `fk_relatorio_ocorrencia1_idx` (`ocorrencia_id` ASC) VISIBLE,
  INDEX `fk_relatorio_funcionario1_idx` (`funcionario_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`telefone` (
  `telefones` VARCHAR(255) NULL DEFAULT NULL,
  `solicitante_id` INT(11) NOT NULL,
  INDEX `fk_telefone_solicitante1_idx` (`solicitante_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defesacivil`.`url_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defesacivil`.`url_foto` (
  `url_foto` LONGTEXT NULL DEFAULT NULL,
  `relatorio_id1` INT(11) NOT NULL,
  INDEX `fk_url_foto_relatorio1_idx` (`relatorio_id1` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
